# Missing value/character list for datasets

missing_codes_accident <- list(
  police_force = NULL,
  accident_severity = NULL,
  number_of_vehicles = -1,
  number_of_casualties = -1,
  date = NULL,
  day_of_week = NULL,
  time = NULL,
  local_authority_district = -1,
  local_authority_ons_district = -1,
  local_authority_highway = -1,
  first_road_class = -1,
  first_road_number = c(-1, 0),
  road_type = c(-1, 9),
  speed_limit = c(-1, 99),
  junction_detail = c(-1, 99),
  junction_control = c(-1, 9),
  second_road_class = c(-1, 9),
  second_road_number = c(-1, 0),
  pedestrian_crossing_human_control = c(-1, 9),
  pedestrian_crossing_physical_facilities = c(-1, 9),
  light_conditions = -1,
  weather_conditions = c(-1, 9),
  road_surface_conditions = c(-1, 9),
  special_conditions_at_site = c(-1, 9),
  carriageway_hazards = c(-1, 9),
  urban_or_rural_area = c(-1, 3),
  did_police_officer_attend_scene_of_accident = c(-1, 3),
  trunk_road_flag = -1,
  lsoa_of_accident_location = c(-1, "-1", NaN, "NULL"),
  accident_index = c(NaN, "NULL"),
  accident_index = c(NaN, "NULL"),
  accident_reference = c(NaN, "NULL"),
  location_easting_osgr = c(NaN, "NULL"),
  location_northing_osgr = c(NaN, "NULL"),
  longitude = c(NaN, "NULL"),
  latitude = c(NaN, "NULL"),
  accident_year = c(NaN, "NULL")
)

missing_codes_vehicle <- list(
  vehicle_reference = NULL,
  vehicle_type = c(-1, 99),
  towing_and_articulation = c(-1, 9),
  vehicle_manoeuvre = c(-1, 99),
  vehicle_direction_from = c(-1, 9),
  vehicle_direction_to = c(-1, 9),
  vehicle_location_restricted_lane = c(-1, 99),
  junction_location = c(-1, 9),
  skidding_and_overturning = c(-1, 9),
  hit_object_in_carriageway = c(-1, 99),
  vehicle_leaving_carriageway = c(-1, 9),
  hit_object_off_carriageway = c(-1, 99),
  first_point_of_impact = c(-1, 9),
  vehicle_left_hand_drive = c(-1, 9),
  journey_purpose_of_driver = c(15, 5, -1, 6),
  sex_of_driver = c(-1, 3),
  age_of_driver = -1,
  age_band_of_driver = -1,
  engine_capacity_cc = -1,
  propulsion_code = -1,
  age_of_vehicle = NULL,
  generic_make_model = -1,
  driver_imd_decile = -1,
  driver_home_area_type = -1,
  lsoa_of_driver = NULL
)

missing_codes_casualty <- list(
  casualty_reference = NULL,
  casualty_class = NULL,
  sex_of_casualty = c(-1, 9),
  age_of_casualty = -1,
  age_band_of_casualty = -1,
  casualty_severity = -1,
  pedestrian_location = c(-1, 10),
  pedestrian_movement = c(-1, 9),
  car_passenger = c(-1, 9),
  bus_or_coach_passenger = c(-1, 9),
  pedestrian_road_maintenance_worker = -1,
  casualty_type = c(-90, 99, -1),
  casualty_imd_decile = -1,
  casualty_home_area_type = -1,
  lsoa_of_casualty = NULL
)